### ISSUE TITLE
Additional configuration: allow maiximum items, or check max-len?

### ISSUE THREAD

**Issue by sevarubbo** [kusotenpa/eslint-plugin-destructuring-newline#1]
Hi there!

Would it be possible to add an extra option to config, e.g. enforcing multiline if there are more than N items?
Or ideally check the max-len rule and enforce this one only if line exceeds max-len?

Thank you!

**Comment by kusotenpa** [comment]
@sevarubbo 
Sorry for the late reply.

Added maxProperties option.
https://github.com/kusotenpa/eslint-plugin-destructuring-newline#option

**Comment by inoyakaigor** [comment]
I think @sevarubbo meant something different than what was implemented.

Let me explain with a pseudocode:
```js
if (destructedProps.length > USER_DEFINED_MAX_PROPS || wholeLineOfCode > USER_DEFINED_MAX_LENGTH) {
  applyRule()
} 
```
the result of this would be:
```js
// input
const { a, b } = obj
const { godDamnLongAsHellPropertyNameNumberOne, godDamnLongAsHellPropertyNameNumberTwo } = obj

// output
const { a, b } = obj
const {
  godDamnLongAsHellPropertyNameNumberOne,
  godDamnLongAsHellPropertyNameNumberTwo
} = obj
```
